### ISSUE TITLE
Start command should pass in Rack config file if present 

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/thin#5]
The Thin server supports passing a Rackup config file via a `-R` flag in the start command. It would be great if the buildpack could detect presence of a `config.ru` flag and set the start command with this config file if it's present.

**Comment by fg-j** [comment]
@paketo-buildpacks/ruby-maintainers Is this still a relevant feature request? Are there any blockers?

**Comment by sophiewigmore** [comment]
As far as I know, it's viable and there are no blockers. I believe this is a reasonable request, since it's use-case supported by Thin already.

**Comment by robdimsdale** [comment]
It looks like thin supports both `-C thin.yml` and `-R config.ru` at the same time, which means we don't have any issues with priority.

Unlike the [thin config feature](https://github.com/paketo-buildpacks/thin/pull/262) I *do not* think we should support a user-provided file location (e.g. via `BP_RACKUP_CONFIG_LOCATION`) because the [Rackup Buildpack](https://github.com/paketo-buildpacks/rackup) does not yet support this, and I think it would be very confusing (and possibly wrong) to support it here and not in that buildpack.

@paketo-buildpacks/ruby-maintainers does anyone have a good way to isolate the `config.ru` portion such that the thin application wouldn't run without the `-R config.ru` flag? I'm not familiar enough with the tools to know if this is possible. If not, I think we can leverage the existing integration test fixture for the thin config file, and validate that `thin -R config.ru -C thin.yml start` runs as expected.
